object Versions {
    const val coreKtx = "1.12.0"
    const val lifecycle = "2.6.2"
    const val activity = "1.8.2"
    const val appcompat = "1.6.1"
    const val material = "1.9.0"
    const val hilt = "2.48"
    const val hiltCompiler = "1.0.0-alpha01"
    const val hiltNavigationCompose = "1.1.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutine = "1.7.3"
}